### ISSUE TITLE
Invalid Security Fix

### ISSUE THREAD

**Issue by mbabker** [joomla-framework/filesystem#46]
Do with this whatever you want, but the security fix stripping `JPATH_ROOT` from exception messages is invalid.  Exception messages are for developers, stripping critical information from them is an invalid fix 100% of the time.

The true problem is that the CMS, with its amateur developer skill level, has next to zero exception handling and a lot of thrown exceptions go unhandled and rendered in the browser.  Exception handling is a first-year developer skill, maybe it should be taught how to handle them in a project with nearly 20 years of technical debt.

**Comment by nibra** [comment]
In principle, I agree with you completely. However, the alternative would have been to check over 10,000 throw statements in the CMS manually. I simply don't have the time or the inclination for that. Hence this pragmatic approach at a central point.

Moreover, a developer who does not know where their root or tmp directory is located has completely different problems; thus the "damage" suffered by the developer is almost zero compared to the benefit for everyone else.
