### ISSUE TITLE
Delete function throws error when it can't chmod

### ISSUE THREAD

**Issue by travisrisner** [joomla-framework/filesystem#61]
### Steps to reproduce the issue
- Create a Joomla package installable file
- Install package on CMS with extension:install command using joomla 4 cli

### Expected result
- Joomla package to install successfully

### Actual result
- Installer fails with an error like below:
err:   Joomla\Filesystem\File::delete: Failed deleting inaccessible file FILENAME.tar.gz    

### System information (as much as possible)
- Ubuntu 18.04
- Joomla 4.4
- PHP8.2
- nginx 1.14.0

### Additional comments
My server infrastructure uses bindfs to ensure certain permissions on all files and folders at all times within the webroot. This prevents certain actions, like chmod from being performed. The error is thrown because the file it is looking to delete cannot be chmod'd technically I suppose. The problem code is [here](https://github.com/joomla-framework/filesystem/blob/php-8.2/src/File.php#L134-L137).

I was able to comment out line 136 in my Joomla install and confirmed the error is gone now and the file deletes as it should. This was not a problem for me until I updated to Joomla 4.4. I believe it might be similar to [this issue](https://github.com/joomla/joomla-cms/issues/23504).

**Comment by Hackwar** [comment]
We have a PR (#70) which removes that check, so I'm closing this PR. Thank you!
